// Generated by emit_tokens.py from brand.json — do not edit.
// Every colour, font and size a deck script uses comes from here.
const path = require("path");
const T = {
  "register": "read",
  "fonts": {
    "heading": "Segoe UI",
    "body": "Segoe UI"
  },
  "colours": {
    "ink": "0B1220",
    "paper": "F0F4F8",
    "accent": "00796B",
    "muted": "94A3B8"
  },
  "palette": {
    "ink": "0B1220",
    "surface": "151E2E",
    "accent": "00796B",
    "paper": "F0F4F8",
    "muted": "94A3B8"
  },
  "scale": {
    "display": 72.0,
    "title": 48.0,
    "h1": 32.0,
    "body": 18.0,
    "caption": 12.0
  },
  "slide": {
    "w": 13.333,
    "h": 7.5
  },
  "margins": {
    "x": 0.667,
    "top": 0.6,
    "bottom": 0.6
  },
  "shape": {
    "corner": "sharp",
    "hairline_pt": 1
  }
};
T.loadPptxgen = function () {
  try { return require("pptxgenjs"); } catch (err) {
    return require(path.join(__dirname, "node_modules", "pptxgenjs"));
  }
};
module.exports = T;
